//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ribalka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int SotrudnikID { get; set; }
        public string SotrudnikName { get; set; }
        public string SotrudnikSurname { get; set; }
        public string SotrudnikMiddleName { get; set; }
        public Nullable<int> IDSklad { get; set; }
    
        public virtual Sklad Sklad { private get; set; }
    }
}
